#higly divisible triangle number
'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''
import math
def divisor(n):
	list_divi=[]
	for i in range(1,int(math.sqrt(n))+1):
		if n% i ==0:
			list_divi.append(i)
			if i != int(n/i):
				list_divi.append(int(n/i))
	return len(list_divi)

def isTriangleNumber(n):
	a=int(math.sqrt(2*n))
	return 0.5*a*(a+1)==n

def lastTerm(n):
	if isTriangleNumber(n):
		return int(math.sqrt(2*n))
	else:
		return None

check=2**4 * 3**4 * 5**4 * 7 * 11

while not isTriangleNumber(check):
	check+=1

seriesLastTerm=lastTerm(check)

while divisor(check)<=500:
	check+=(seriesLastTerm+1)
	seriesLastTerm+=1

print(check)
